from doctor_raven.features.git_ops.auto_commit import is_idle, try_auto_commit
from doctor_raven.features.git_ops.hygiene_scanner import HygieneFinding
from doctor_raven.features.git_ops.models import SecretFinding
from doctor_raven.features.git_ops.registry import disable, enable, is_enabled, list_enabled
from doctor_raven.features.git_ops.repo_ops import (
    branch_exists,
    checkout_remote_tracking,
    commit,
    create_branch,
    current_branch,
    draft_commit_message,
    gitignore_status,
    has_changes,
    has_upstream,
    is_detached_head,
    push,
    push_set_upstream,
    repo_root,
    scan_outgoing,
    scan_staged,
    scan_staged_hygiene,
    stage_all,
    staged_files,
    stash_list,
    stash_pop,
    stash_push,
    switch_branch,
    unpushed_commit_count,
)

__all__ = [
    "HygieneFinding",
    "SecretFinding",
    "branch_exists",
    "checkout_remote_tracking",
    "commit",
    "create_branch",
    "current_branch",
    "disable",
    "draft_commit_message",
    "enable",
    "gitignore_status",
    "has_changes",
    "has_upstream",
    "is_detached_head",
    "is_enabled",
    "is_idle",
    "list_enabled",
    "push",
    "push_set_upstream",
    "repo_root",
    "scan_outgoing",
    "scan_staged",
    "scan_staged_hygiene",
    "stage_all",
    "staged_files",
    "stash_list",
    "stash_pop",
    "stash_push",
    "switch_branch",
    "try_auto_commit",
    "unpushed_commit_count",
]
